pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'javac -d out src/**/*.java'
            }
        }
        stage('Test') {
            steps {
                echo 'No tests configured.'
            }
        }
        stage('Execute') {
            steps {
                sh 'java -cp out Main'
            }
        }
    }
}